### ISSUE TITLE
Architecture Diagram needs to be updated

### ISSUE THREAD

**Issue by odrodrig** [IBM/SmartContractTrading-wFabric1-4-VSCodeExt#7]
I'm still seeing the mock up of the architecture diagram in the README rather than the finished version.

**Comment by ljbennett62** [comment]
@odrodrig - hmmm...not sure what happened - as I thought I had updated it - let me try again..

**Comment by ljbennett62** [comment]
@odrodrig - this has been updated - can you close out the issue. tx
