### ISSUE TITLE
packaging the contract issue

### ISSUE THREAD

**Issue by sharkberto** [IBM/SmartContractTrading-wFabric1-4-VSCodeExt#9]
There is a missing step in tutorial to close the loop on how to package the contract before starting the local fabric, right? What I mean is, it didn't seem to detect the contract I had open in the UI

**Comment by sharkberto** [comment]
![image](https://user-images.githubusercontent.com/4588331/59465597-1cfc5380-8de0-11e9-815d-be70750de93f.png)

**Comment by ljbennett62** [comment]
@sharkberto - so I didn't need to do anything.  I wonder if you have more than one contract - you need to select the one you want to run.
